//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_FrameWork_DataBase_FirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int id { get; set; }
        public string addr { get; set; }
    }
}
